# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Analyze, test, and build the APK"
  lane :validate do
    validate_pr
  end

  desc "Run PR validation checks for Android/Flutter app"
  lane :validate_pr do
    # Fastfile lives in android/fastlane; go two levels up to Flutter app root.
    project_root = File.expand_path("../..", __dir__)
    Dir.chdir(project_root) do
      sh("flutter pub get")
      sh("flutter analyze")
      sh("flutter test")
      sh("flutter build apk")
    end
  end
end
